# This is a basic workflow to help you get started with Actions
# https://www.youtube.com/watch?v=Yg5rpke79X4
name: My-gith-action-2
env:
  key_sha_var:  "sha${{ github.sha }}"
# Controls when the action will run. 
on:
  push:
    branches:
      - main #master
jobs:
  my-testin:
    runs-on: ubuntu-latest
    steps:
      - name: хеловорлд
        run: |
          echo Hello, world!
          echo "Current key_var is ${{ env.key_sha_var }}"
          ls -al #выдаст пустой каталог в докере

      - name: гит клон май репо
        uses: actions/checkout@v1 #типа клонируем данные
        
      - name: глянем что склонировалось
        run: 
          ls -al #выдаст склонированный каталог в докере
                    
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testin]
    steps:
      - name: деплойворлд
        run: |
          echo Деплойед
          aws --version
          zip
