# This is a basic workflow to help you get started with Actions

name: My-gith-action-2

# Controls when the action will run. 
on:
  push:
    branches:
      - main #master
jobs:
  my-testin:
    runs-on: ubuntu-latest
    steps:
      - name: хеловорлд
        run: echo Hello, world!
  my-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: деплойворлд
        run: echo Деплойед
